### PR TITLE
Recursive process of Admin Boundaries for internal boundary processing.

### PR DESCRIPTION
**Pull request by geojayuu**
User defines supplier at command prompt ie. GADM; Geoboundaries etc.
ie,
snakemake transform_internal_boundaries --config supplier='gadm' --cores 1

### CODE REVIEW

**Comment by SteveP2000** [comment]
Hi @geojayuu , when running
`snakemake transform_internal_boundaries --config supplier='gadm' --cores 1`
I get the following
`raw_data\geobnd_adm1.zip`
Looks like the supplier is assigned to the incorrect type?

**Comment by geojayuu** [comment]
I hadn't committed all necessary files. This was a mistake, These should be in place now.

**Comment by geojayuu** [comment]
I was able to replicate this if I ran in master which produced the same error. I had to switch to the branch being committed (internal_boundaries) then run 'pip install .'

**Review by leonbaruah — APPROVED** [review]
Is all good - I'll make a note of the admin2 bug and create a new branch to try and fix it

**Pull request merged**
